version: "3.7"

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: on-failure

  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    restart: on-failure